overrides:
  ceph:
    log-whitelist:
    - reached quota
    - wrongly marked me down
  conf:
    global:
      osd_max_object_name_len: 800
tasks:
- install:
- ceph:
- workunit:
    clients:
      client.0:
        - rados/test.sh
        - rados/test_pool_quota.sh

